name: Push to Docker hub
run-name: "Push to docker hub: ${{ github.actor }} 🚀"
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  Build-Linux:
    uses: supergoongaming/sharedWorkflows/.github/workflows/image_build.yml@master
    with:
      image_name: enf3rno/sg_ddns
      build_number: ${{ github.run_number }}
      dockerfile_location: ./Dockerfile
    secrets: inherit
